#!/usr/bin/env python

import sys
from time import sleep

import install
if install.__init__():
    print('librarys had been installed.')
import interface

URL_TEXT_DIRECTORY = 'URL.txt'
ID_TEXT_DIRECTORY = 'PASSWORD.txt'
SURVEY_TEXT_DIRECTORY = 'SURVEY.txt'

def main():
    app = interface.QApplication(sys.argv)
    ui = interface.MainWindow(URL_TEXT_DIRECTORY, ID_TEXT_DIRECTORY, SURVEY_TEXT_DIRECTORY)
    sys.exit(app.exec_())
        
if __name__ == '__main__':
    main()

